/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Renzo
 */
public class VistaListaClientes extends javax.swing.JPanel {

    /**
     * Creates new form VistaListaClientes
     */
    public VistaListaClientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jpListaClientes = new javax.swing.JPanel();
        pnlHeadCliente = new javax.swing.JPanel();
        labTituloCliente = new javax.swing.JLabel();
        pnlBuscarUsuario1 = new javax.swing.JPanel();
        labBuscarUsuario1 = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 32767));
        txtBuscarUsuarioCliente = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnBuscarCliente = new javax.swing.JButton();
        pnlTablaCliente = new javax.swing.JPanel();
        scrlTablaCliente = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        jPanel19 = new javax.swing.JPanel();
        labInfo5 = new javax.swing.JLabel();
        labInfo6 = new javax.swing.JLabel();
        pnlBotonesCliente = new javax.swing.JPanel();
        btnSalirCliente = new javax.swing.JButton();

        jpListaClientes.setPreferredSize(new java.awt.Dimension(400, 500));
        jpListaClientes.setLayout(new java.awt.BorderLayout(5, 5));

        pnlHeadCliente.setPreferredSize(new java.awt.Dimension(193, 100));
        pnlHeadCliente.setLayout(new java.awt.GridLayout(3, 0, 0, 5));

        labTituloCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labTituloCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labTituloCliente.setText("Listado de Clientes");
        labTituloCliente.setPreferredSize(new java.awt.Dimension(168, 20));
        pnlHeadCliente.add(labTituloCliente);

        pnlBuscarUsuario1.setPreferredSize(new java.awt.Dimension(200, 40));
        pnlBuscarUsuario1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        labBuscarUsuario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labBuscarUsuario1.setText("Buscar por Usuario: ");
        pnlBuscarUsuario1.add(labBuscarUsuario1);
        pnlBuscarUsuario1.add(filler5);

        txtBuscarUsuarioCliente.setPreferredSize(new java.awt.Dimension(150, 35));
        pnlBuscarUsuario1.add(txtBuscarUsuarioCliente);

        pnlHeadCliente.add(pnlBuscarUsuario1);

        btnBuscarCliente.setText("BUSCAR");
        jPanel6.add(btnBuscarCliente);

        pnlHeadCliente.add(jPanel6);

        jpListaClientes.add(pnlHeadCliente, java.awt.BorderLayout.PAGE_START);

        pnlTablaCliente.setMaximumSize(new java.awt.Dimension(2147483647, 180));
        pnlTablaCliente.setPreferredSize(new java.awt.Dimension(579, 400));
        pnlTablaCliente.setRequestFocusEnabled(false);
        pnlTablaCliente.setLayout(new java.awt.BorderLayout());

        scrlTablaCliente.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrlTablaCliente.setMaximumSize(new java.awt.Dimension(32767, 370));
        scrlTablaCliente.setPreferredSize(new java.awt.Dimension(452, 300));

        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nombre", "Apellidos", "E-mail", "Teléfono", "Usuario", "Dirección"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbClientes.setMaximumSize(new java.awt.Dimension(450, 300));
        tbClientes.setPreferredSize(new java.awt.Dimension(450, 350));
        tbClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbClientesMouseClicked(evt);
            }
        });
        scrlTablaCliente.setViewportView(tbClientes);

        pnlTablaCliente.add(scrlTablaCliente, java.awt.BorderLayout.PAGE_START);

        jPanel19.setLayout(new java.awt.GridLayout(2, 0));

        labInfo5.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        labInfo5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labInfo5.setText("Seleccione una fila para eliminar al Cliente correspondiente.");
        labInfo5.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        labInfo5.setMaximumSize(new java.awt.Dimension(411, 20));
        labInfo5.setPreferredSize(new java.awt.Dimension(411, 20));
        jPanel19.add(labInfo5);

        labInfo6.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        labInfo6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labInfo6.setText("NOTA: No puede eliminar clientes que han realizado alguna solicitud en el sistema");
        labInfo6.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        labInfo6.setMaximumSize(new java.awt.Dimension(411, 20));
        labInfo6.setPreferredSize(new java.awt.Dimension(411, 20));
        jPanel19.add(labInfo6);

        pnlTablaCliente.add(jPanel19, java.awt.BorderLayout.PAGE_END);

        jpListaClientes.add(pnlTablaCliente, java.awt.BorderLayout.CENTER);

        pnlBotonesCliente.setPreferredSize(new java.awt.Dimension(82, 35));

        btnSalirCliente.setText("Salir");
        pnlBotonesCliente.add(btnSalirCliente);

        jpListaClientes.add(pnlBotonesCliente, java.awt.BorderLayout.PAGE_END);

        jScrollPane1.setViewportView(jpListaClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 525, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbClientesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbClientesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarCliente;
    public javax.swing.JButton btnSalirCliente;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpListaClientes;
    private javax.swing.JLabel labBuscarUsuario1;
    private javax.swing.JLabel labInfo5;
    private javax.swing.JLabel labInfo6;
    private javax.swing.JLabel labTituloCliente;
    private javax.swing.JPanel pnlBotonesCliente;
    private javax.swing.JPanel pnlBuscarUsuario1;
    private javax.swing.JPanel pnlHeadCliente;
    private javax.swing.JPanel pnlTablaCliente;
    private javax.swing.JScrollPane scrlTablaCliente;
    public javax.swing.JTable tbClientes;
    public javax.swing.JTextField txtBuscarUsuarioCliente;
    // End of variables declaration//GEN-END:variables
}
