/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Renzo
 */
public class VistaEmpleadoSolicitudesSeguimiento extends javax.swing.JPanel {

    /**
     * Creates new form VistaEmpleadoSolicitudesLista
     */
    public VistaEmpleadoSolicitudesSeguimiento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrlTablaSolicitudes2 = new javax.swing.JScrollPane();
        tbSolicitudes = new javax.swing.JTable();
        pnlFiltroEstado = new javax.swing.JPanel();
        labFiltroEstado = new javax.swing.JLabel();
        filler4 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 32767));
        cbxFiltrarEstadoSol = new javax.swing.JComboBox<>();
        filler9 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(100, 0), new java.awt.Dimension(15, 32767));
        btnActualizarListaSol = new javax.swing.JButton();
        labTitulo = new javax.swing.JLabel();
        labSubTitulo2 = new javax.swing.JLabel();
        scrlTablaEvaluaciones = new javax.swing.JScrollPane();
        tbEvaluaciones = new javax.swing.JTable();
        labInfo2 = new javax.swing.JLabel();
        labInfo1 = new javax.swing.JLabel();

        scrlTablaSolicitudes2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrlTablaSolicitudes2.setMaximumSize(new java.awt.Dimension(32767, 200));
        scrlTablaSolicitudes2.setPreferredSize(new java.awt.Dimension(452, 150));

        tbSolicitudes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"123", "QUEJA", "Luis Gonzales", "12-05-2020", "FINALIZADO", "Gerencia"}
            },
            new String [] {
                "ID", "Tipo de Solicitud", "Cliente", "Fecha Ingreso", "Estado actual", "Departamento Evaluador"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbSolicitudes.setMaximumSize(new java.awt.Dimension(450, 200));
        tbSolicitudes.setPreferredSize(new java.awt.Dimension(450, 200));
        tbSolicitudes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbSolicitudesMouseClicked(evt);
            }
        });
        scrlTablaSolicitudes2.setViewportView(tbSolicitudes);

        pnlFiltroEstado.setPreferredSize(new java.awt.Dimension(200, 40));
        pnlFiltroEstado.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 5));

        labFiltroEstado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labFiltroEstado.setText("Filtrar por Estado: ");
        pnlFiltroEstado.add(labFiltroEstado);
        pnlFiltroEstado.add(filler4);

        cbxFiltrarEstadoSol.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "En Espera", "En Trámite", "Finalizado" }));
        cbxFiltrarEstadoSol.setMaximumSize(new java.awt.Dimension(100, 80));
        pnlFiltroEstado.add(cbxFiltrarEstadoSol);
        pnlFiltroEstado.add(filler9);

        btnActualizarListaSol.setText("Actualizar Lista de Solicitudes");
        pnlFiltroEstado.add(btnActualizarListaSol);

        labTitulo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labTitulo.setText("Listado de seguimiento");

        labSubTitulo2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labSubTitulo2.setText("Seguimiento de la Solicitud seleccionada");

        scrlTablaEvaluaciones.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        scrlTablaEvaluaciones.setMaximumSize(new java.awt.Dimension(32767, 100));
        scrlTablaEvaluaciones.setPreferredSize(new java.awt.Dimension(452, 100));

        tbEvaluaciones.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número Evaluación", "Fecha", "Hora", "Estado", "Evaluador"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbEvaluaciones.setMaximumSize(new java.awt.Dimension(450, 200));
        tbEvaluaciones.setPreferredSize(new java.awt.Dimension(450, 140));
        tbEvaluaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbEvaluacionesMouseClicked(evt);
            }
        });
        scrlTablaEvaluaciones.setViewportView(tbEvaluaciones);

        labInfo2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        labInfo2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labInfo2.setText("Seleccione una fila para mostrar los detalles y comentarios de la Evaluación correspondiente.");
        labInfo2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        labInfo2.setMaximumSize(new java.awt.Dimension(411, 20));
        labInfo2.setPreferredSize(new java.awt.Dimension(411, 20));

        labInfo1.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        labInfo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labInfo1.setText("Seleccione una fila para mostrar el seguimiento");
        labInfo1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        labInfo1.setMaximumSize(new java.awt.Dimension(411, 20));
        labInfo1.setPreferredSize(new java.awt.Dimension(411, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrlTablaSolicitudes2, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addComponent(pnlFiltroEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(labTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labSubTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrlTablaEvaluaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, 596, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(labTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFiltroEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrlTablaSolicitudes2, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(labInfo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(labSubTitulo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrlTablaEvaluaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labInfo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tbSolicitudesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbSolicitudesMouseClicked

    }//GEN-LAST:event_tbSolicitudesMouseClicked

    private void tbEvaluacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbEvaluacionesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbEvaluacionesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnActualizarListaSol;
    public javax.swing.JComboBox<String> cbxFiltrarEstadoSol;
    private javax.swing.Box.Filler filler4;
    private javax.swing.Box.Filler filler9;
    private javax.swing.JLabel labFiltroEstado;
    private javax.swing.JLabel labInfo1;
    private javax.swing.JLabel labInfo2;
    private javax.swing.JLabel labSubTitulo2;
    private javax.swing.JLabel labTitulo;
    private javax.swing.JPanel pnlFiltroEstado;
    private javax.swing.JScrollPane scrlTablaEvaluaciones;
    private javax.swing.JScrollPane scrlTablaSolicitudes;
    private javax.swing.JScrollPane scrlTablaSolicitudes1;
    private javax.swing.JScrollPane scrlTablaSolicitudes2;
    public javax.swing.JTable tbEvaluaciones;
    public javax.swing.JTable tbSolicitudes;
    // End of variables declaration//GEN-END:variables
}
