/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Renzo
 */
public class VistaEmpleadoEmpleadosLista extends javax.swing.JPanel {

    /**
     * Creates new form VistaEmpleadoSolicitudesLista
     */
    public VistaEmpleadoEmpleadosLista() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jpListaEmpleados = new javax.swing.JPanel();
        pnlHeadEmpleado = new javax.swing.JPanel();
        labTituloEmpleado = new javax.swing.JLabel();
        pnlBuscarUsuario2 = new javax.swing.JPanel();
        labBuscarUsuario2 = new javax.swing.JLabel();
        filler6 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(55, 0), new java.awt.Dimension(15, 32767));
        txtBuscarUsuarioEmpleado = new javax.swing.JTextField();
        pnlBuscarDepartamento = new javax.swing.JPanel();
        labBuscarDepartamento = new javax.swing.JLabel();
        filler7 = new javax.swing.Box.Filler(new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 0), new java.awt.Dimension(20, 32767));
        cbxBuscarDepartamento = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        btnBuscarEmpleado = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbEmpleados = new javax.swing.JTable();

        jScrollPane1.setBorder(null);

        jpListaEmpleados.setPreferredSize(new java.awt.Dimension(400, 500));
        jpListaEmpleados.setLayout(new java.awt.BorderLayout(5, 5));

        pnlHeadEmpleado.setPreferredSize(new java.awt.Dimension(193, 135));
        pnlHeadEmpleado.setLayout(new java.awt.GridLayout(4, 0, 0, 5));

        labTituloEmpleado.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labTituloEmpleado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labTituloEmpleado.setText("Listado de Empleados");
        labTituloEmpleado.setPreferredSize(new java.awt.Dimension(168, 20));
        pnlHeadEmpleado.add(labTituloEmpleado);

        pnlBuscarUsuario2.setPreferredSize(new java.awt.Dimension(200, 40));
        pnlBuscarUsuario2.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        labBuscarUsuario2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labBuscarUsuario2.setText("Buscar por Usuario: ");
        pnlBuscarUsuario2.add(labBuscarUsuario2);
        pnlBuscarUsuario2.add(filler6);

        txtBuscarUsuarioEmpleado.setPreferredSize(new java.awt.Dimension(150, 35));
        pnlBuscarUsuario2.add(txtBuscarUsuarioEmpleado);

        pnlHeadEmpleado.add(pnlBuscarUsuario2);

        pnlBuscarDepartamento.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 3));

        labBuscarDepartamento.setText("Buscar por Departamento: ");
        pnlBuscarDepartamento.add(labBuscarDepartamento);
        pnlBuscarDepartamento.add(filler7);

        cbxBuscarDepartamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Atención al Cliente", "Calidad", "Ventas", "Gerencia", "Contabilidad y Finanzas" }));
        pnlBuscarDepartamento.add(cbxBuscarDepartamento);

        pnlHeadEmpleado.add(pnlBuscarDepartamento);

        btnBuscarEmpleado.setText("BUSCAR");
        jPanel7.add(btnBuscarEmpleado);

        pnlHeadEmpleado.add(jPanel7);

        jpListaEmpleados.add(pnlHeadEmpleado, java.awt.BorderLayout.PAGE_START);

        tbEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Apellidos", "E-mail", "Teléfono", "Usuario", "Departamento"
            }
        ));
        jScrollPane2.setViewportView(tbEmpleados);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 652, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
        );

        jpListaEmpleados.add(jPanel1, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(jpListaEmpleados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 465, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarEmpleado;
    public javax.swing.JComboBox<String> cbxBuscarDepartamento;
    private javax.swing.Box.Filler filler6;
    private javax.swing.Box.Filler filler7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel jpListaEmpleados;
    private javax.swing.JLabel labBuscarDepartamento;
    private javax.swing.JLabel labBuscarUsuario2;
    private javax.swing.JLabel labTituloEmpleado;
    private javax.swing.JPanel pnlBuscarDepartamento;
    private javax.swing.JPanel pnlBuscarUsuario2;
    private javax.swing.JPanel pnlHeadEmpleado;
    public javax.swing.JTable tbEmpleados;
    public javax.swing.JTextField txtBuscarUsuarioEmpleado;
    // End of variables declaration//GEN-END:variables
}
