/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

/**
 *
 * @author Renzo
 */
public class VistaEmpleadoClientesEliminar extends javax.swing.JPanel {

    /**
     * Creates new form VistaEmpleadoSolicitudesLista
     */
    public VistaEmpleadoClientesEliminar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jpListaClientes = new javax.swing.JPanel();
        pnlHeadCliente = new javax.swing.JPanel();
        labTituloCliente = new javax.swing.JLabel();
        pnlBuscarUsuario1 = new javax.swing.JPanel();
        labBuscarUsuario1 = new javax.swing.JLabel();
        filler5 = new javax.swing.Box.Filler(new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 0), new java.awt.Dimension(15, 32767));
        txtBuscarUsuarioCliente = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        btnBuscarCliente = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbClientes = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jScrollPane1.setBorder(null);

        jpListaClientes.setPreferredSize(new java.awt.Dimension(400, 500));
        jpListaClientes.setLayout(new java.awt.BorderLayout(5, 5));

        pnlHeadCliente.setPreferredSize(new java.awt.Dimension(193, 100));
        pnlHeadCliente.setLayout(new java.awt.GridLayout(3, 0, 0, 5));

        labTituloCliente.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        labTituloCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labTituloCliente.setText("Eliminar clientes");
        labTituloCliente.setPreferredSize(new java.awt.Dimension(168, 20));
        pnlHeadCliente.add(labTituloCliente);

        pnlBuscarUsuario1.setPreferredSize(new java.awt.Dimension(200, 40));
        pnlBuscarUsuario1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));

        labBuscarUsuario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labBuscarUsuario1.setText("Buscar por Usuario: ");
        pnlBuscarUsuario1.add(labBuscarUsuario1);
        pnlBuscarUsuario1.add(filler5);

        txtBuscarUsuarioCliente.setPreferredSize(new java.awt.Dimension(150, 35));
        pnlBuscarUsuario1.add(txtBuscarUsuarioCliente);

        pnlHeadCliente.add(pnlBuscarUsuario1);

        btnBuscarCliente.setText("BUSCAR");
        jPanel6.add(btnBuscarCliente);

        pnlHeadCliente.add(jPanel6);

        jpListaClientes.add(pnlHeadCliente, java.awt.BorderLayout.PAGE_START);

        tbClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombre", "Apellidos", "E-mail", "Teléfono", "Usuario", "Dirección"
            }
        ));
        jScrollPane3.setViewportView(tbClientes);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel1.setText("Seleccione una fila para eliminar al Cliente correspondiente.");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel2.setText("NOTA: No puede eliminar clientes que han realizado alguna solicitud en el sistema");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jpListaClientes.add(jPanel1, java.awt.BorderLayout.CENTER);

        jScrollPane1.setViewportView(jpListaClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 491, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBuscarCliente;
    private javax.swing.Box.Filler filler5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JPanel jpListaClientes;
    private javax.swing.JLabel labBuscarUsuario1;
    private javax.swing.JLabel labTituloCliente;
    private javax.swing.JPanel pnlBuscarUsuario1;
    private javax.swing.JPanel pnlHeadCliente;
    public javax.swing.JTable tbClientes;
    public javax.swing.JTextField txtBuscarUsuarioCliente;
    // End of variables declaration//GEN-END:variables
}
